version: "3.9"
services:
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=buying_frenzy
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    image: buying-frenzy:latest
    depends_on:
      postgres:
            condition: service_healthy
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      - POSTGRES_HOST=postgres