// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/google/wire"
)

// Injectors from wire.go:
func InitApplication(ctx context.Context) (*ApplicationContext, func(), error) {
	config, err := ProvideConfig()
	if err != nil {
		return nil, nil, err
	}
	db := ProvidePostgreDB(config)
	repo := ProvideStorage(db)
	applicationContext := &ApplicationContext{
		ctx: ctx,
		db:  repo,
	}
	return applicationContext, func() {
	}, nil
}

// wire.go:

var ApplicationSet = wire.NewSet(
	ProvideConfig,
	ProvidePostgreDB,
	ProvideStorage,
)
